GET https://localhost:7021/api/campeonato/listar

###

POST https://localhost:7021/api/campeonato/cadastrar
Content-Type: application/json

{
    "nome": "Copa do Brasil",
    "premiacao": 10000000
}

###

GET https://localhost:7021/api/campeonato/consultar/10

###

DELETE https://localhost:7021/api/campeonato/deletar/2

###

PUT https://localhost:7021/api/campeonato/atualizar/10
Content-Type: application/json

{
    "nome": "Copa do Brasil",
    "premiacao": 18000000
}

###

GET https://localhost:7021/api/campeonato/analisar/2

###

GET https://localhost:7021/api/campeonato/classificacao/4

###

GET https://localhost:7021/api/campeonato/classificacaoDetalhes/2

### 

GET https://localhost:7021/api/campeonato/finalizar/4
