GET https://localhost:7021/api/campeonato/listar

###

POST https://localhost:7021/api/campeonato/cadastrar
Content-Type: application/json

{
    "nome": "Copa do Brasil",
    "premiacao": 10000000
}

###

GET https://localhost:7021/api/campeonato/consultar/1

###

DELETE https://localhost:7021/api/campeonato/deletar/1

###

PUT https://localhost:7021/api/campeonato/atualizar/1
Content-Type: application/json

{
    "nome": "Campeonato Carioca",
    "premiacao": 18000000
}

###

GET https://localhost:7021/api/campeonato/analisar/1

###

GET https://localhost:7021/api/campeonato/classificacao/1

###

GET https://localhost:7021/api/campeonato/classificacaoDetalhes/1

### 

GET https://localhost:7021/api/campeonato/finalizar/1
