GET https://localhost:7021/api/confronto/listar

###

POST https://localhost:7021/api/confronto/cadastrar
Content-Type: application/json

{
    "timeCasaId": 1,
    "timeForaId": 2,
    "campeonatoId": 4,
    "gols_time_casa": 3,
    "gols_time_fora": 2
}

###

GET https://localhost:7021/api/confronto/consultar/1

###