GET https://localhost:7021/api/tabela/listar

###

POST https://localhost:7021/api/tabela/cadastrar
Content-Type: application/json

{
    "campeonatoId": 4,
    "timeId": 2
}

###
GET https://localhost:7021/api/tabela/consultar/4

