GET https://localhost:7021/api/tabela/listar

###

POST https://localhost:7021/api/tabela/cadastrar
Content-Type: application/json

{
    "campeonatoId": 1,
    "timeId": 1
}

###

POST https://localhost:7021/api/tabela/cadastrar
Content-Type: application/json

{
    "campeonatoId": 1,
    "timeId": 2
}

###

POST https://localhost:7021/api/tabela/cadastrar
Content-Type: application/json

{
    "campeonatoId": 1,
    "timeId": 3
}

###

POST https://localhost:7021/api/tabela/cadastrar
Content-Type: application/json

{
    "campeonatoId": 1,
    "timeId": 4
}

###
GET https://localhost:7021/api/tabela/consultar/1

