GET https://localhost:7021/api/time/listar

###

POST https://localhost:7021/api/time/cadastrar
Content-Type: application/json

{
    "nome": "Flamengo"
}

###

POST https://localhost:7021/api/time/cadastrar
Content-Type: application/json

{
    "nome": "Fluminense"
}

###

POST https://localhost:7021/api/time/cadastrar
Content-Type: application/json

{
    "nome": "Vasco"
}

###

POST https://localhost:7021/api/time/cadastrar
Content-Type: application/json

{
    "nome": "Botafogo"
}

###

GET https://localhost:7021/api/time/consultar/19

###

DELETE https://localhost:7021/api/time/deletar/21

###

PUT https://localhost:7021/api/time/atualizar/21
Content-Type: application/json

{
    "nome": "Girona"
}

###

GET https://localhost:7021/api/time/historico/6
